name: LiangShi_Auto_v3
on:
  push:
  workflow_dispatch:
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install pandas numpy
      - run: python main.py
        env:
          MY_SENDER: ${{ secrets.MY_SENDER }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
          MY_RECEIVER: ${{ secrets.MY_RECEIVER }}
